export const theme = {
  grid: {
    lg: '132rem',
  },
  font: {
    family: 'Inter',
    letterSpacing: {
      sm: '0.02em',
      md: '0.04em',
    },
    weigths: {
      regular: 400,
      medium: 500,
      semiBold: 600,
      bold: 700,
    },
    sizes: {
      disclaimer: '1.2rem',
      small: '1.4rem',
      paragraph: '1.6rem',
      large: '1.8rem',
      subtitle: '3.2rem',
      title: '4rem',
      extraTitle: '4.8rem',
    },
    lineHeights: {
      small: '4rem',
      subtitle: '4.8rem',
      paragraph: '3.2rem',
      large: '2.8rem',
      extraTitle: '5.6rem',
    },
  },
  colors: {
    white: '#ffffff',
    gray100: '#dfe3eb',
    purple50: '#f0edff',
    gray500: '#a5a5a5',
    primaryDark: '#242424',
    secondaryPink: '#ed1ca6',
    secondaryPurple: '#7d00ff',
    secondaryOrange: '#ff8718',
  },
  space: {
    0: '0.4rem',
    1: '0.8rem',
    2: '1.2rem',
    3: '1.4rem',
    4: '1.6rem',
    5: '2.4rem',
    6: '3.2rem',
    7: '4rem',
    8: '4.8rem',
    9: '5.2rem',
  },
  borderRadius: {
    rounded: '50%',
    button: '0.5rem',
    card: '0.6rem',
    sm: '0.4rem',
    md: '0.5rem',
    lg: '0.8rem',
  },
  transitions: {
    slow: '0.5s',
    fast: '0.2s',
  },
}
