export enum Assets {
  Background = '/bg-header.png',
  About = '/computer.png',
  ImgWork1 = '/imgwork1.png',
  ImgWork2 = '/imgwork2.png',
  ImgWork3 = '/imgwork3.png',
  ImgWork4 = '/imgwork4.png',
  ImgWork5 = '/imgwork5.png',
  ImgWork6 = '/imgwork6.png',
  Dot = '/dot.svg',
  LogoYoutube = '/youtubelogo.svg',
  LogoSketch = '/sketchlogo.svg',
  LogoGoogle = '/googlelogo.svg',
  LogoAdobe = '/adobelogo.svg',
  Logo = '/logo.svg',
  Quote = '/quote.svg',
  Shapes = '/shapes.svg',
}
